### ISSUE TITLE
Manual's "Engine Development > Logic Nodes" page is missing key information

### ISSUE THREAD

**Issue by Gerkinfeltser** [armory3d/armory_docs#14]
Though armory_docs/dev/logicnodes.md contains the necessary code, the online manual's Logic Nodes' page is missing some of the lines of code necessary for both the blender.py & TestNode.hx. The custom node doesn't work or display without these lines.

Missing from the blender.py script:
`
from bpy.types import Node
from arm.logicnode.arm_nodes import *
import arm.nodes_logic
`

Missing from TestNode.hx
`
package armory.logicnode;
`

Furthermore, the paths where these files should be placed could use a bit more clarity

**Comment by luboslenco** [comment]
Fixed!
