### ISSUE TITLE
doc contribution

### ISSUE THREAD

**Issue by creutzerb** [armory3d/armory_docs#33]
Hello,

I would like to contribute to the doc, most specifically to the api, by the addition of small descriptions when I deem it could help new users.

Am I welcome to do so, even though I am new here and my knowledge of armory3d is quite shallow ?
Do I just edit the html code or is there a better way to do it ?
Did I miss existing guidelines on the subject ?

Sorry if that wasn't the appropriate place for these questions.

**Comment by zicklag** [comment]
If you want to contribute to the API documentation, that is actually done by adding comments to the code. The code comments are used to automatically generate the documentation site. For example:

```haxe
/**
 * RigidBody is used to allow objects to interact with Physics in your game including collisions and gravity.
 * RigidBody can also be used with the getContacts method to detect collisions and run appropriate code.
 * The Bullet physics engine is used for these calculations.
 */
@:access(armory.trait.physics.bullet.PhysicsWorld)
class RigidBody extends iron.Trait {
```

If you want to add some documentation to the a function, just add a comment above the function in the source file.

Don't worry about not knowing too much about the API, I'm sure if you write something that is inaccurate it will get mentioned when you submit a PR. Any help we can get with documentation is greatly appreciated! :smiley:

**Comment by luboslenco** [comment]
Feel welcome to post if there are more questions!
