### ISSUE TITLE
Offline manual?

### ISSUE THREAD

**Issue by BlackGoku36** [armory3d/armory_docs#37]
How to convert Armory's Docs(including api documentation) to pdf or any other format for offline reading?

**Comment by luboslenco** [comment]
You can download this repo and view the markdown files in VSCode / KodeStudio / etc. Not aware of pdf conversion but there should be some markdown tooling available for that. 🙂 

Some more info [here](https://armory3d.org/manual/#/dev/contribute?id=contributing-docs).

![1](https://user-images.githubusercontent.com/3685704/57547714-5ebc5900-735f-11e9-9356-b3dacc19f6d7.PNG)

**Comment by BlackGoku36** [comment]
@luboslenco  It is legal to download whole [api manual](https://armory3d.org/manual/api/) right?, becaused i used [HTTrack](http://www.httrack.com/html/index.html) to download that whole api documentation

**Comment by luboslenco** [comment]
Yes. The api is part of this repo here:
https://github.com/armory3d/armory_docs/tree/master/api
