### ISSUE TITLE
Logic Nodes creating not working

### ISSUE THREAD

**Issue by KluSim** [armory3d/armory_docs#7]
I tried to reproduce the example, but after writing the .py file and restarting Blender the Console says
```
Traceback (most recent call last):
  File "C:/Users/SK/Desktop/Armory/Armory/armsdk//armory/blender\arm\handlers.py", line 253, in on_load_post
    import blender
  File "C:\Users\SK\Desktop\Armory\blends\a/Libraries/mynodes\blender.py", line 1, in <module>
    class TestNode(Node, ArmLogicTreeNode):
NameError: name 'Node' is not defined
```
The node doesn't show up anywhere in the Logic Nodes editor. I used the exact same python code, and the folders are correctly set up. 
https://github.com/armory3d/armory_docs/blob/master/dev/logicnodes.md

**Comment by luboslenco** [comment]
I added missing imports to the https://github.com/armory3d/armory_docs/blob/master/dev/logicnodes.md, should be ok now.

Pre-set example at:
https://github.com/armory3d/armory_examples/tree/master/dev_logicnode

**Comment by KluSim** [comment]
Thanks, got it working! Already created my first node, "Inverse", that activates the the node being plugged into when it isn't being asked to run itself. Is there a place/will there be a place, where community-made nodes can be submitted to may be implemented in standard Armory?

**Comment by luboslenco** [comment]
That's awesome! Created a new repository for logic nodes:
https://github.com/armory3d/logic_pack

If you submit pull-request with your node please remove the existing TestNode in logic_pack.:) We can then also move core nodes straight into armory like you mentioned.
